# Ch.24_Exception_Handling
How to use the Try-Except block in Python
